### ISSUE TITLE
Travis skips some tests

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#162]
Here are the test logs from AppVeyor and Travis for PR #158:
* https://ci.appveyor.com/project/serin-delaunay/wangscape/build/0.1.239#L1772
* https://travis-ci.org/Wangscape/Wangscape/jobs/260838067#L776

Appveyor runs 156 tests from 64 test cases, and Travis runs 146 tests from 60 cases. The missing test cases are `TestBitmap` (new in the PR), `TestCalculatorLinear`, `TestRasterImage`, and `TestRasterValues`.

Travis was previously configured to skip some tests that required OpenGL functions, but that argument was removed and none of these test cases would have been affected.

- [ ] Travis should run the `TestBitmap`, `TestCalculatorLinear`, `TestRasterImage`, and `TestRasterValues` test cases.

**Comment by cheukyin699** [comment]
I can work on this.
