### ISSUE TITLE
GUI interface for option specification

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#17]
At the moment all configuration is done through editing a JSON file. This tool should be usable by non-programmers, so a GUI interface will eventually be needed.

Ideally, such a tool should also provide quick feedback about the effects of altered options - showing one or more example tiles immediately rather than writing all the tileset images.

It may also be nice to have the tileset example application (#10) accessible from or integrated with the GUI editor. But it would be OK to wait for full tileset generation before using that.

- [ ] GUI option editor
- [ ] Integrated example tile generator
- [ ] Access/integrate with landscape viewer (#10)

**Comment by serin-delaunay** [comment]
This will be low-priority until the options specification becomes less volatile, or a solution is found that autogenerates the GUI from the options schema.

**Comment by hryniuk** [comment]
How do you feel about using **Qt** for this? It will be a nice learning opportunity for me 😄. We could discuss input options during this week and I think I'll be able to start around the coming weekend.

**Comment by serin-delaunay** [comment]
Qt would be a good choice for this.

**Comment by serin-delaunay** [comment]
Closed in #159. There are still points here to resolve, but they can be split into separate issues now.
