### ISSUE TITLE
"Select options file" is hidden behind the "File" menu; should be an obvious button.

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#178]
That's the one of things that are hard at the beginning of GUI creation - how `Wangscape`'s menu bar should look like? Beside menu bar, there are several buttons - maybe they also should be hidden or they're not needed (e.g. tileset could be generated automatically after options loading and on every change).

1. For now it's:
    - File
        * Load options
        * Open options editor
        * Save output
1. It could be more like this:
    - File
        * Save output
    - Options
        * Load
        * Open editor
        * [Save?]
        * [Restore?]

But usually, in other programs, there are `Edit` or `Tools` submenus. What if we would like to add `Undo` and `Redo` buttons? Where should we place them? They can be related to both options and tileset generation, i.e. as a user I may want to restore previous tileset, but keep options used for generation (by the way, that's quite good idea for a feature ;)).

@serin-delaunay is 2. ok? Do you have different ideas? What about other buttons, e.g. `Generate`?

**Comment by serin-delaunay** [comment]
2. looks good for the menu bar. Perhaps the best place for `Load options`, `Undo`, and `Redo` buttons would be as icons on a toolbar (with tooltips)?

**Comment by hryniuk** [comment]
Hmm... I think the best would be moving "Save" next to the "Generate" button. It will be perfectly obvious that "Save" is connected to just generated tileset. "Load options" could become just "Load" button at the top of options editor and options editor could be opened just by clicking some icon; an arrow seems to be ideal (it will toggle "Options Editor" window :)) ◀️.

**Comment by serin-delaunay** [comment]
When the user starts the program they will probably want to do one of two things: load an options file, or autogenerate options from a list of images. I think it makes sense to have the options editor open from the start.

**Comment by hryniuk** [comment]
Yes, I meant that after closing it, it could be reopened by a button with proper icon.
