### ISSUE TITLE
Annoying warning messages about CRLF and LF at prompt

### ISSUE THREAD

**Issue by bluehood** [Wangscape/Wangscape#208]
Hi,
here's how it looks when I clone the repo and `cd` into it. I have no idea how this works but, out of the box, I get a dirty workspace (`Wangscape/noise/module/codecs/CMakeLists.txt` seems to be modified on the fly) and warning messages after every command.

This is in bash, on Ubuntu 16.04.

```
marvin:~$ cd Scratchpad/Wangscape/
warning: CRLF will be replaced by LF in Wangscape/noise/module/codecs/CMakeLists.txt.
The file will have its original line endings in your working directory.

marvin:Wangscape (master *)$ ls
CMakeLists.txt      LICENSE         Wangscape      WangscapeTest  build-spotify-json.bat  travis-osx.sh
CODE_OF_CONDUCT.md  README.md       Wangscape.sln  appveyor.yml   doc                     travis-ubuntu.sh
CONTRIBUTING.md     STYLE_GUIDE.md  WangscapeGui   build          lib
warning: CRLF will be replaced by LF in Wangscape/noise/module/codecs/CMakeLists.txt.
The file will have its original line endings in your working directory.

marvin:Wangscape (master *)$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Wangscape/noise/module/codecs/CMakeLists.txt

no changes added to commit (use "git add" and/or "git commit -a")
warning: CRLF will be replaced by LF in Wangscape/noise/module/codecs/CMakeLists.txt.
The file will have its original line endings in your working directory.
marvin:Wangscape (master *)$ 
```

**Comment by bluehood** [comment]
Alright it's the first time I collaborate with people using windows, so took me some time to realize this is git and it's expected behaviour: https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important

Whether you want to keep `Wangscape/noise/module/codecs/CMakeLists.txt` with CRLF is up to you, that seems to be the only file with this issue.

**Comment by serin-delaunay** [comment]
If that's the only file affected, it makes sense to have it conform with the other `CMakeLists.txt` files. Feel free to open a PR for it.

**Comment by bluehood** [comment]
@serin-delaunay there you go
