### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#29]
It will be nice to have a logger with a command line option, e.g. `-v` to print (to stdin or a file) what's going on. After quick googling I think for Wangscape it will be the best to roll its own small logger.

**Comment by serin-delaunay** [comment]
Yes, that would be a good idea.

Some of the details that should be logged are currently written to the output JSON files, but those files are intended for use by programs that consume the output tilesets. A log file would be valuable for humans debugging Wangscape's output.

**Comment by hryniuk** [comment]
There are a few commented out lines, so I think it will be much better to throw them out and allow logging there (where it's really relevant).

**Comment by hryniuk** [comment]
So... I'll do it. You can assign me to it, if it will help you to organize the project :).

**Comment by hryniuk** [comment]
For now, in #34, I'm adding only a new way of arguments parsing in a case you'd like to use/change it soon. For this issue, #29, there could be two options, e.g. `-v` and `-vv` to enable logging at all and enable all kinds of logs, I'll push PR with a proposal this weekend.

There will be a small problem with input images handling (we talked about in #21). If we make them positional arguments, then order of arguments will matter (if I understand `boost::program_options` properly). I think it would be better to require explicit `--option-file` argument, but it will break compatibility with the previous verions.

**Comment by serin-delaunay** [comment]
Breaking compatibility isn't a problem at the moment, since the program isn't ready for general use yet.

**Comment by hryniuk** [comment]
Yet :smile:!
