### ISSUE TITLE
Object fields initialization

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#36]
I see that Wangscape uses the same name for constructor arguments as for class attributes (in `TilesetGenerator`). It could be a problem after changing (or removing) name of any argument. Consider this example:

```cpp
#include <iostream>

struct A
{
    A(int /* a */)
        : a(a)
    {}
    int a;
};

int main()
{
    A a(3);
    std::cout << a.a << "\n";
}
```
It compiles (at least without warnings flag, it should be an error in my opinion) and runs. `std::cout` prints e.g.:
```bash
> ./h
-1654812272
> ./h
1764974992
> ./h
-807848544
> ./h
-1030225712
> ./h
1040083440
```

...and because of that, I want to suggest adding `_` suffix to class members (and enable all warning flags + treat warnings as errors) to emphasise the difference between them and constructor's arguments, so after attribute name removal it will be:
```cpp
#include <iostream>

struct A
{
    A(int /* a */)
        : a_(a)
    {}
    int a_;
};

int main()
{
    A a(3);
    std::cout << a.a_ << "\n";
}
```
and won't compile at all. I noticed there is a `m` prefix in (at least) one class - that's another way to do it :). Maybe there could be a small `CONTRIBUTING.md` file with some style/naming rules (that's good example for me: https://github.com/openstreetmap/osm2pgsql/blob/master/CONTRIBUTING.md)? I think we could use one of formatting tools to check it (code style) during Travis build (as soon as it will work). I linked already my [cpp project](https://github.com/hryniuk/cpp) in one of comments - it uses the clang-format tool ([configuration file](https://github.com/hryniuk/cpp/blob/master/.clang-format)).

**Comment by serin-delaunay** [comment]
> I see that Wangscape uses the same name for constructor arguments as for class attributes (in `TilesetGenerator`). It could be a problem after changing (or removing) name of any argument. Consider this example:
> `[snip]`
> It compiles (at least without warnings flag, it should be an error in my opinion) and runs. `std::cout` prints e.g.:
> `[snip]`
> ...and because of that, I want to suggest adding `_` suffix to class members (and enable all warning flags + treat warnings as errors) to emphasise the difference between them and constructor's arguments, so after attribute name removal it will be:
> `[snip]`
> and won't compile at all. I noticed there is a `m` prefix in (at least) one class - that's another way to do it :).
I don't plan to use unnamed parameters in constructors (the most likely use cases for them are callbacks, virtual functions, and post-increment/decrement operators). But the codebase is still unstable and there is a possibility that changes like that may be made accidentally. So, it would be worthwhile to require differently named data variables and contructor parameters.

I prefer to keep classes' public interfaces as clean as possible, so the trailing underscores would have to be in the parameter names. `m` prefixes are used in private and protected data members.
>  Maybe there could be a small `CONTRIBUTING.md` file with some style/naming rules (that's good example for me: https://github.com/openstreetmap/osm2pgsql/blob/master/CONTRIBUTING.md)? I think we could use one of formatting tools to check it (code style) during Travis build (as soon as it will work). I linked already my [cpp project](https://github.com/hryniuk/cpp) in one of comments - it uses the clang-format tool ([configuration file](https://github.com/hryniuk/cpp/blob/master/.clang-format)).
Yes, a contributing guide and automatic format checking would be a worthwhile addition to the project. Once the architecture of the code is more settled it would be a good idea to choose a documentation tool and format.

**Comment by serin-delaunay** [comment]
As of https://github.com/Wangscape/Wangscape/commit/3119049e1331e95ff1123d86f95ebeed068c2275 there are no more constructor parameters sharing their name with a data member, so this can be closed. We can open a separate issue for automatic format checking.
