### ISSUE TITLE
Add examples and diagrams to documentation

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#42]
Now that the program actually generates corner Wang tiles, it would be good to illustrate what they look like and how they should be used, either in README.md or on a wiki page. This is an image generating tool, and it should be described with images.

**Comment by hryniuk** [comment]
Beside that I think it would be valuable to have a `docs/` dir with an info about used algorithms and project structure (the latter will be placed in `CONTRIBUTING.md` I suppose).

**Comment by serin-delaunay** [comment]
Yes, documenting how tileset generation works will be important part of making the tool accessible, and project structure should be explained in `CONTRIBUTING.md` (added to #41).

This is a separate issue, though - to gain interest and users, the project's main page should show clear and immediate examples of what kind of input it needs and what kind of results it can produce.

**Comment by serin-delaunay** [comment]
Some images to be used in the front page README.md:
![gervais-terrain-3](https://cloud.githubusercontent.com/assets/15715657/23166703/8cfa561c-f839-11e6-8c43-bdd54cd9a4f7.png)
![wangscape-squares-sample](https://cloud.githubusercontent.com/assets/15715657/23166720/a0e63a9c-f839-11e6-9b6b-1393204cb0c2.png)
![wangscape-natural-sample](https://cloud.githubusercontent.com/assets/15715657/23166724/a3d6dbb2-f839-11e6-8e1c-4654cb2a11f6.png)
![wangscape-natural-sample-grid](https://cloud.githubusercontent.com/assets/15715657/23166727/a5bf4f86-f839-11e6-84f7-2530d5fcbfa7.png)
![wangscape-options-sample](https://cloud.githubusercontent.com/assets/15715657/23166825/0720fbb2-f83a-11e6-8f48-7a2345dc2444.PNG)
![wangscape-module-sample](https://cloud.githubusercontent.com/assets/15715657/23166827/08b9c30a-f83a-11e6-9e47-d4fe31dea779.PNG)

Probably they should be moved elsewhere later.
