### ISSUE TITLE
Project split

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#43]
Hey,

do you consider splitting what's callled Wangscape now (with Wangscape, WangscapeTest and Wangview "subprojects") into separate projects (tests should stay with a source code, that's clear)?

It may seem counterintuitive for now, but I'm not very confident if adding an another separate application (I mean that GUI application, under "Issues", for options; Wangview is already one) is a good idea. As I see all of them will be linked by options and output format and that's a problem, but it could be resolved with proper versioning (or setting final format of them :wink:).

The big advantage of keeping them together is ease of reusing code between these modules (e.g. codecs and adding Python bindings for Wangview). With separate projects, there should be **probably** some base to use as submodule for all of them.

What's you opinion on this?

**Comment by serin-delaunay** [comment]
Wangscape already has three different executables, a fourth is proposed, and if the common code is moved to a separate library we'll have five different projects... It's definitely a good idea to split them up.

I think it would be best to host the projects in an organisation account for Wangscape, to make sure the inactive ones don't get buried.

**Comment by serin-delaunay** [comment]
I'm making the organisation now, so this repository's moving to https://github.com/Wangscape/Wangscape.

**Comment by hryniuk** [comment]
Nice, that's what I thought about :smile:.

**Comment by hryniuk** [comment]
Wangview was already moved to a separate repository and **for now** the only thing that **could** be done in this issue is renaming `Wangscape` to `src` and `WangscapeTest` to `test`/`tst`... but that's not a part of "split".

* **for now**: `metaoutput` has become a library and it could be moved to another repository as well, cause it will be most likely needed in the Qt tool for options generation; we will see
* **could**: it's just a quite common _convention_; I leave this decision to @serin-delaunay

**Comment by serin-delaunay** [comment]
I think renaming to `src` and `test` should be done soon (after #50 is merged).

The Qt tool for options generation should eventually be able to generate sample tiles, and even invoke the tileset generator without needing to use the command line. When that happens, probably metaoutput codecs, options codecs, noise, and tile generation should all be moved into one or more library repositories. Then Wangscape would be quite a thin wrapper, just calling library methods in order.

I don't think that needs to be done immediately, though; we can move features into libraries when the Qt tool needs them.
