### ISSUE TITLE
Tests parameters are hard-coded, in different files

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#44]
It should be:
* common test fixture
* config file (path to it passed as command line argument)
* command line argument (a path to `example_options.json`)

**Comment by serin-delaunay** [comment]
Test parameters should definitely be made more flexible. I would prefer not to have obligatory command-line parameters in the test executable, so there should be a test config file with the path to `example_options.json`, a hardcoded default location for it, and an optional command line argument to specify a different one.

**Comment by hryniuk** [comment]
We could move this test options to `WangscapeTest` directory to state explicitly that this file is a part of tests.

**Comment by serin-delaunay** [comment]
Yes, the test config file should definitely be in `WangscapeTest` folder.

The examples shouldn't be in the test folder; they're meant not just as test data, but also as demonstrations and templates for end users to build on.

**Comment by hryniuk** [comment]
I think that examples shouldn't be in a source code directory as well.

So... maybe the problem is just a current project structure? It will be a bit better to have some "standard structure". We could move current content of the `Wangscape` dir up and have `examples` under `doc` dir e.g.:
```
|- doc/
    |- examples/
        |- example_1
        |- example_2
        |- ...
        |- example_n
|- lib/
|- src/
|- test/ [or tst/]
```

It's just a suggestion, it could be next PR to merge (with a little discussion before) after those three that we've got now :wink:.

**Comment by serin-delaunay** [comment]
Yes, `doc/examples/` is probably the best place fot the examples. `test/` will be fine for the tests.

**Comment by serin-delaunay** [comment]
I think this is fixed now. Restructuring the project folder structure is really a different issue.
