### ISSUE TITLE
Place for discussions

### ISSUE THREAD

**Issue by hryniuk** [Wangscape/Wangscape#66]
I need a chat to discuss things that not necessarily fit comments under issues/PR (e.g. now I've got some problems with libnoise to talk about). Could we have one? Other projects have different ways to communicate, sometimes more than one:
* IRC
* mailing list
* web chat.

As the last option is the easiest one for us I think, I would like to suggest [Gitter](https://gitter.im). I've checked and only organization's owner has right to create it, so I you agree with me, @serin-delaunay, create a room for Wangscape, please ("Add room/ do you want to start a community for one of your **github projects**" on gitter page)?

**Comment by serin-delaunay** [comment]
I like IRC, but Gitter is probably better for project discussion because it keeps logs. Here it is:

https://gitter.im/Wangscape/Lobby#

**Comment by hryniuk** [comment]
I like IRC too, but Gitter chat is easier to join for GitHub users and a bit more friendly for people with little experience.
