### ISSUE TITLE
using namespace declarations in *codec.h files

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#75]
We have `using namespace spotify::json::codec` declarations in all the options and metaoutput `*codec.h` header files. This moves everything in the `spotify::json::codec` namespace into the global namespace in all files which include either `MetaOutput.h` or `OptionsManager.h`. `spotify::json::codec` has some names like `map`, `string`, `shared_ptr` which could collide with `std` versions if someone forgets to type `std::` or makes a declaration like `using std::map`.

All `using namespace spotify::json::codec` declarations should be removed, replaced with a brief name like `using namespace sjc = spotify::json::codec`, or replaced with `using` declarations for individual members of the namespace.

I should have caught this in code review, sorry!

**Comment by hryniuk** [comment]
Thanks :). I've noticed that, but didn't catch, how important it is. I thought rather about keeping this `using` clause and putting all these functions in our `codecs` namespace (so it will be `metaoutput::codecs`) to stick to directory-namespace mapping convention.

It should be checked how it will influence the `encode`/`decode` calls (it we can make it use implicitly proper `default_codec_t` instance).

**Comment by serin-delaunay** [comment]
I think putting our `codec` classes in a namespace other than `spotify::json` will be more trouble than it's worth; they use a lot of names from spotify::json, and when more complex codecs are required (#28) there will be even more.

The `encode`/`decode` calls in `Metaoutput.cpp` and `OptionsManager.cpp` all use the full namespaced identifiers, so they shouldn't be affected.
